{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    },
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::976851222302:role/k8s-eks-scaling-demo-cluster20190207180317090900000001"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}